### ISSUE TITLE
Old dependencies in last 1.6 release

### ISSUE THREAD

**Issue by jensborch** [palantir/documentalist#220]
It would be nice with a new release with update dependencies. Some dependencies like marked are quite old. I could do a PR to update as many none breaking dependencies as possible, if someone are ready to review and hopefully merge the changes.

**Comment by adidahiya** [comment]
We're on [v4.0](https://github.com/palantir/documentalist/blob/b01b7806dd9b266f71ae3acc70c8e526e0f682cc/packages/compiler/package.json#L3), see the package.json files and README.

The Github "Releases" section is irrelevant at this time.

Our dependencies are mostly up-to-date, except for typedoc, which requires quite a bit of work to update to latest: https://github.com/palantir/documentalist/pull/156

**Comment by jensborch** [comment]
@adidahiya Thanks, I totally missed that. I will look into migrating the projects I work on to the new @documentalist/compiler dependency
