### ISSUE TITLE
Add React support out of the box

### ISSUE THREAD

**Issue by jaredpalmer** [palantir/documentalist#44]
Hey all. I’d realllllllly like to use this instead of storybook. I know that the React plugin and all is in blueprint source, but it seems heavily tied into blueprint’s build / gulp tasks. It would be nice if documentalist came with React support and an example of a React theme / output out of the box.

**Comment by giladgray** [comment]
@jaredpalmer adding React support is out of the scope of this package: its sole purpose is to generate documentation data, _not_ to render it. the [blueprint docs package](https://github.com/palantir/blueprint/tree/master/packages/docs) is that example of a React theme, and it's published to NPM so can be used directly out of its box.

**Comment by giladgray** [comment]
also check out the [docs-data package](https://github.com/palantir/blueprint/blob/master/packages/docs-data/compile-docs-data#L45-L64) for how we actually use documentalist in blueprint: note there's nothing React-specific about the usage. all the React stuff lives in that docs package.
