### ISSUE TITLE
handlebars ambient types HACKHACK

### ISSUE THREAD

**Issue by adidahiya** [palantir/documentalist#87]
tracking

**Comment by adidahiya** [comment]
blocked on https://github.com/TypeStrong/typedoc/pull/1022

**Comment by styu** [comment]
@adidahiya should we try and use `@gerrit0/typedoc` until an actual release is made for typedoc? (as per https://github.com/TypeStrong/typedoc/pull/1052#issuecomment-508777871) I feel like we've been waiting for a long time, and I'd like to get documentalist onto the latest version of TypeScript

**Comment by adidahiya** [comment]
fixed by #103
