### ISSUE TITLE
Potential typo in the lerna.json

### ISSUE THREAD

**Issue by Mike-Dax** [palantir/documentalist#95]
I'm not sure if this is intentional or not, but the lerna.json has:

```
"userWorkspaces": true,
```

I'm pretty sure that should be:

```
"useWorkspaces": true,
```

If that's correct, I can make a PR trivially.

**Comment by lukasbach** [comment]
@Mike-Dax is right, lerna did not work for me on the project as is, but it did work with the suggested change. This bug makes it harder for new contributors because they will encounter an error on setting up the project.
